# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 15.x
        
    #Instalar as dependências NPM/YARN
    - name: Install dependencies
      run: yarn
      
    #Executar a build
    - name: Run Build
      run: yarn buid
    
    #Copiar código para servidor
    - name: copy file via ssh to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "tests/a.txt,tests/b.txt"
        target: "test"


